### ISSUE TITLE
0.5.3 on pypi isn't the newest code

### ISSUE THREAD

**Issue by bradharmon** [pushyrpc/pushy#54]
I know this isn't maintained anymore, but is there any chance you could push the latest code to pypi?  0.5.3 on pypi doesn't have your latest commit f79cfad4caadf03219a3c26a925814c5dce3c4aa.

**Comment by axw** [comment]
Uploaded a new release, 0.5.4, which includes the fix. Let me know if you're interested in becoming a maintainer, and I can add you to this repo and pypi too.

**Comment by bradharmon** [comment]
Yes, I would be interested in that.  Thanks for the offer.

**Comment by axw** [comment]
@bradharmon I've sent you an invitation to join the repo. If you send me your pypi username, I'll add you there too.
